// Generated by scripts/generate-table-rules-subset.ts from public/rules.json.
// Keep public/rules.json as the source of truth; rerun the script after rule mechanics changes.
import type { DisciplineRule } from '@/modules/table/utils/discipline-ui'

export const tableRulesSubset = {
  "disciplines": {
    "Мощь": {
      "powers": {
        "1": {
          "Смертоносность": {
            "mechanics": {
              "activation": {
                "action": "none",
                "kind": "passive"
              },
              "automation": {
                "status": "auto"
              },
              "effects": [
                {
                  "amount": {
                    "discipline": "Мощь",
                    "formula": "discipline_rating"
                  },
                  "id": "potence-lethal-body-ignore-armor",
                  "label": "Смертоносность: броня",
                  "matcher": {
                    "attackTypes": [
                      "unarmed",
                      "brawl"
                    ],
                    "owners": [
                      "source"
                    ],
                    "targets": [
                      "health"
                    ]
                  },
                  "operation": "ignore_armor",
                  "type": "damage_modifier"
                },
                {
                  "id": "potence-lethal-body-mortals",
                  "label": "Смертоносность: тяжёлый урон смертным",
                  "matcher": {
                    "attackTypes": [
                      "unarmed",
                      "brawl"
                    ],
                    "creatureTypes": [
                      "mortal",
                      "human"
                    ],
                    "owners": [
                      "source"
                    ],
                    "severities": [
                      "superficial"
                    ],
                    "targets": [
                      "health"
                    ]
                  },
                  "operation": "convert_damage_type",
                  "severity": "aggravated",
                  "type": "damage_modifier"
                }
              ]
            }
          }
        }
      }
    },
    "Стойкость": {
      "powers": {
        "1": {
          "Сила жизни": {
            "mechanics": {
              "activation": {
                "action": "none",
                "kind": "passive"
              },
              "automation": {
                "status": "auto"
              },
              "effects": [
                {
                  "amount": {
                    "discipline": "Стойкость",
                    "formula": "discipline_rating"
                  },
                  "operation": "add_max",
                  "tracker": "health",
                  "type": "tracker_modifier"
                }
              ]
            }
          }
        }
      }
    }
  }
} as const

export const tableDefaultDisciplineRules = tableRulesSubset.disciplines as unknown as Record<string, DisciplineRule>
