import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

type JsonObject = Record<string, unknown>

const ROOT_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const INPUT_FILE = resolve(ROOT_DIR, 'public/rules.json')
const OUTPUT_FILE = resolve(ROOT_DIR, 'modules/table/rules-subset.ts')
const INCLUDED_PASSIVE_EFFECT_TYPES = new Set([
  'tracker_modifier',
  'damage_modifier',
])

function isObject(value: unknown): value is JsonObject {
  return Boolean(value && typeof value === 'object' && !Array.isArray(value))
}

function sortEntries<T>(entries: Array<[string, T]>) {
  return entries.sort(([left], [right]) => (left < right ? -1 : left > right ? 1 : 0))
}

function sortKeysDeep(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortKeysDeep)
  if (!isObject(value)) return value

  return Object.fromEntries(
    sortEntries(Object.entries(value))
      .map(([key, nested]) => [key, sortKeysDeep(nested)]),
  )
}

function isPassiveActivation(mechanics: JsonObject) {
  const activation = mechanics.activation
  if (typeof activation === 'string') return activation === 'passive'
  if (!isObject(activation)) return false
  return activation.passive === true
    || activation.type === 'passive'
    || activation.mode === 'passive'
    || activation.kind === 'passive'
}

function getPassiveEffects(power: JsonObject) {
  const mechanics = isObject(power.mechanics) ? power.mechanics : null
  if (!mechanics || !isObject(mechanics.automation)) return null
  if (
    mechanics.automation.status !== 'auto'
    && mechanics.automation.status !== 'partial'
  ) return null
  if (!isPassiveActivation(mechanics)) return null
  if (!Array.isArray(mechanics.effects) || mechanics.effects.length === 0) return null

  const effects = mechanics.effects.filter((effect) => (
    isObject(effect)
    && typeof effect.type === 'string'
    && INCLUDED_PASSIVE_EFFECT_TYPES.has(effect.type)
  ))
  if (effects.length === 0) return null

  return {
    activation: mechanics.activation,
    automation: mechanics.automation,
    effects,
  }
}

function getPowerContainer(value: JsonObject) {
  if (isObject(value.powers)) return value.powers
  const levelEntries = Object.entries(value).filter(([key]) => (
    Number.isFinite(Number(key))
  ))
  return levelEntries.length > 0
    ? Object.fromEntries(levelEntries)
    : null
}

function extractPowers(value: unknown) {
  if (!isObject(value)) return null

  const levels: JsonObject = {}
  for (const [level, powers] of sortEntries(Object.entries(value))) {
    if (!Number.isFinite(Number(level)) || !isObject(powers)) continue

    const levelPowers: JsonObject = {}
    for (const [powerName, power] of sortEntries(Object.entries(powers))) {
      if (!isObject(power)) continue
      const mechanics = getPassiveEffects(power)
      if (!mechanics) continue
      levelPowers[powerName] = { mechanics }
    }

    if (Object.keys(levelPowers).length > 0) levels[level] = levelPowers
  }

  return Object.keys(levels).length > 0 ? levels : null
}

function extractDiscipline(discipline: unknown) {
  if (!isObject(discipline)) return null

  const subset: JsonObject = {}
  const powers = extractPowers(discipline.powers)
  if (powers) subset.powers = powers

  if (isObject(discipline.paths)) {
    const paths: JsonObject = {}
    for (const [pathName, path] of sortEntries(Object.entries(discipline.paths))) {
      if (!isObject(path)) continue
      const pathPowerContainer = getPowerContainer(path)
      const pathPowers = extractPowers(pathPowerContainer)
      if (pathPowers) paths[pathName] = { powers: pathPowers }
    }
    if (Object.keys(paths).length > 0) subset.paths = paths
  }

  return Object.keys(subset).length > 0 ? subset : null
}

function buildSubset(rulesJson: unknown) {
  if (!isObject(rulesJson) || !isObject(rulesJson.disciplines)) {
    throw new Error('public/rules.json does not contain a disciplines object')
  }

  const disciplines: JsonObject = {}
  for (const [disciplineName, discipline] of sortEntries(Object.entries(rulesJson.disciplines))) {
    const subset = extractDiscipline(discipline)
    if (subset) disciplines[disciplineName] = subset
  }

  return sortKeysDeep({ disciplines })
}

const rulesJson = JSON.parse(readFileSync(INPUT_FILE, 'utf8')) as unknown
const subset = buildSubset(rulesJson)
const json = JSON.stringify(subset, null, 2)

writeFileSync(
  OUTPUT_FILE,
  `// Generated by scripts/generate-table-rules-subset.ts from public/rules.json.\n`
    + `// Keep public/rules.json as the source of truth; rerun the script after rule mechanics changes.\n`
    + `import type { DisciplineRule } from '@/modules/table/utils/discipline-ui'\n\n`
    + `export const tableRulesSubset = ${json} as const\n\n`
    + `export const tableDefaultDisciplineRules = tableRulesSubset.disciplines as unknown as Record<string, DisciplineRule>\n`,
)
